Dataflux-U-nidos/Backend

src/infrastructure/config/config.ts, src/infrastructure/config/index.ts, src/infrastructure/database/database.ts, src/infrastructure/database/index.ts, src/server.ts, src/shared/utils/index.ts, src/shared/utils/validateEnv.ts
Stablished the basic connection to the MongoDB Atlas cluster.
--- 
* Created basic utils validator 
* Created basic config file
* Created the database connection class
* Imported the database connection in the `server.ts` file
--- 
It is imperative that every one has the `.env` file configured with at least the `MONGO_URI` var, to ensure the correct functioning of the server
=> 86a79qp1a - Config database cluster

bun.lock, package.json, src/application/dtos/index.ts, src/application/dtos/major.dto.ts, src/application/index.ts, src/application/use-cases/index.ts, src/application/use-cases/major/create-major.use-case.ts, src/application/use-cases/major/delete-major.use-case.ts, src/application/use-cases/major/get-all-majors.use-case.ts, src/application/use-cases/major/get-major-by-id.use-case.ts, src/application/use-cases/major/update-major.use-case.ts, src/domain/entities/index.ts, src/domain/entities/major.entity.ts, src/domain/index.ts, src/domain/repositories/index.ts, src/domain/repositories/major.repository.ts, src/infrastructure/database/index.ts, src/infrastructure/database/models/index.ts, src/infrastructure/database/models/major.model.ts, src/infrastructure/database/repositories/index.ts, src/infrastructure/database/repositories/major.repository.impl.ts, src/infrastructure/index.ts, src/presentation/controllers/index.ts, src/presentation/controllers/major.controller.ts, src/presentation/index.ts, src/presentation/routes/index.ts, src/presentation/routes/major.router.ts, src/server.ts, src/shared/utils/typebox-validator.ts
Creating data model contract for the entity Major
--- 
* Created Major entity
* Created indexes
* Created Major DTO
* Created Major Controller
* Created Major routes
* Created Major model
* Created Major repositories
=> 86a77yf32 - Major data contract creation

src/infrastructure/database/repositories/index.ts, src/presentation/routes/major.router.ts
Fix importing issues in the index file
=> 🚑 fix: Importing issues

package-lock.json, src/application/dtos/jobOpportunities.dto.ts, src/application/use-cases/jobOpportunities/create-jobOpportunities.use-case.ts, src/application/use-cases/jobOpportunities/delete-jobOpportunities.use-case.ts, src/application/use-cases/jobOpportunities/get-all-jobOpportunities.use-case.ts, src/application/use-cases/jobOpportunities/get-jobOpportunities-by-id.use-case.ts, src/application/use-cases/jobOpportunities/update-jobOpportunities.use-case.ts, src/domain/entities/jobOpportunities.entity.ts, src/domain/repositories/jobOpportunities.repository.ts, src/infrastructure/database/models/jobOpportunities.model.ts, src/infrastructure/database/repositories/jobOpportunities.repository.impl.ts, src/presentation/controllers/jobOpportunities.controller.ts, src/presentation/routes/jobOpportunities.router.ts
modifies the JobOpportunities schema to store a reference to the job (jobId) instead of keeping a full list of jobs (jobs[]).
=> 86a77yfwu - Change jobs array to jobId reference in job opportunities

.github/workflows/ci-test.yml, Dockerfile
Creating dockerfile and adding steps to build the image and deploy it to ECR when a merge happen in main and release branches
Created Dockerfiile
Implemented steps to build and upload images to ECR
=> 86a75bz9c - Github actions Pipeline

Dockerfile
Updated Dockerfile
Updated Dockerfile
=> 86a75bz9c - updated dockerfile

.github/workflows/ci-test.yml
Modified pipeline to trigger when push
=> 86a75bz9c - modified pipeline

src/application/dtos/educational_institution.dto.ts, src/application/use-cases/educational-institution/create-educational-institution.use-case.ts, src/application/use-cases/educational-institution/delete-educational-institution.use-cases.ts, src/application/use-cases/educational-institution/get-all-educational-institution.use-case.ts, src/application/use-cases/educational-institution/get-educational-institution-by-id.use-case.ts, src/application/use-cases/educational-institution/update-educational-institution.use-case.ts, src/domain/entities/educational-institution.entity.ts, src/domain/repositories/educational-institution.repository.ts, src/infrastructure/database/models/educational-institution.model.ts, src/presentation/controllers/educational-institution.controller.ts, src/presentation/routes/educational-institution.router.ts
- Correccción de imports de algunos archivos
- Corrección de la interface event y todos sus usos asociados
=> 🐛 error (86a77ycub) corection of import errors and event interface

src/application/dtos/index.ts, src/application/dtos/user.dto.ts, src/application/use-cases/index.ts, src/application/use-cases/user/create-user.use-case.ts, src/application/use-cases/user/delete-user.use-case.ts, src/application/use-cases/user/get-all-users.use-case.ts, src/application/use-cases/user/get-user-by-id.use-case.ts, src/application/use-cases/user/update-user.use-case.ts, src/domain/entities/index.ts, src/domain/entities/user.entity.ts, src/domain/repositories/index.ts, src/domain/repositories/user.repository.ts, src/infrastructure/database/models/index.ts, src/infrastructure/database/models/user.model.ts, src/infrastructure/database/repositories/index.ts, src/infrastructure/database/repositories/user.repository.impl.ts, src/presentation/controllers/index.ts, src/presentation/controllers/user.controller.ts, src/presentation/routes/index.ts, src/presentation/routes/major.router.ts, src/presentation/routes/user.router.ts, src/server.ts
This pull request introduces a complete User CRUD implementation following Clean Architecture principles, using Mongoose for database operations
--- 
- **Domain**: Created user entities (e.g., `TUser`, `UserType`) and a repository interface (`IUserRepository`).
- **Infrastructure**: Implemented the user repository (`UserRepositoryImpl`) with Mongoose.
- **Application**: 
- Added use cases for creating, reading, updating, and deleting users.
- Introduced DTOs for input (`CreateUserDto`, `UpdateUserDto`) and output (`UserResponseDto`, `UsersListDto`), ensuring sensitive data (e.g., password) is not exposed.
- **Presentation**:
- Created the `UserController` to handle HTTP requests.
- Set up user routes for all CRUD operations (`create`, `get`, `getAll`, `update`, `delete`).
- …
=> ✨ Feature(86a77yd13): Creating user data contract

src/infrastructure/config/config.ts, src/server.ts
Changed the api routes from http://localhost:3000/user to http://localhost:3000/api/v1/user 
So all routes no are changed with the /api/v1
Apart from this the .env file should ne change with the new click up version
=> :recycle: (86a7ahgy7) Refactored all api routes and changed .env

README.md
This PR adds a README with all the instructions to use the backend.
README
=> Documentation: agregation of README

src/application/dtos/comment.dto.ts, src/domain/entities/comment.entity.ts, src/infrastructure/database/models/comment.model.ts, src/infrastructure/database/repositories/comment.repository.impl.ts, src/presentation/controllers/comment.controller.ts
This PR adds createdAt and updatedAt fields to comment collection by updating models, domain entities, DTOs, repositories, and controllers.
Timestamp has been added recently and it works fine, however eslint gave me an error when running the backend
---
- Models: Added { timestamps: true } in comment.model.ts.
- Entities/DTOs: Updated to include createdAt and updatedAt.
- Repositories: Mapped the new timestamp fields in responses.
- Controllers: Endpoints now return timestamps.
---
=> 🚑 ✨ creating timestamp data for comment (problems with eslint)

src/application/dtos/major.dto.ts, src/application/use-cases/major/create-major.use-case.ts, src/application/use-cases/major/delete-major.use-case.ts, src/application/use-cases/major/get-all-majors.use-case.ts, src/application/use-cases/major/get-major-by-id.use-case.ts, src/application/use-cases/major/update-major.use-case.ts, src/domain/repositories/major.repository.ts, src/infrastructure/database/repositories/major.repository.impl.ts
The CRUD implementation was modified to use Major's DTOs.
Institution difficulty type was fixed to match Major's model.
- Major's dto.
- Major's use-cases.
- Major's repository.
=> ♻️ Refactor: update major use cases and repository to use IMajorRepository and MajorResponseDto

src/server.ts
This pr ensures code readability and good programming practices
--- 
* Removed unnecesary comments in the `server.ts` file
=> (86a7hqqyp) testing branch

src/presentation/routes/comment.router.ts, src/presentation/routes/educationalInstitution.router.ts, src/presentation/routes/jobOpportunity.router.ts, src/presentation/routes/major.router.ts, src/presentation/routes/user.router.ts
Middleware validation was integrated into comment, educational institution, job opportunity, major, and user routes.  
- comment.router.ts  
- educationalInstitution.router.ts
- jobOpportunity.router.ts
- major.router.ts
- user.router.ts
=> ♻️ Refactor (86a7duxx9): add role validation middleware to routes 

.github/workflows/ci-test.yml
=> Deploy settigs

bun.lock
dependencies in bun.lock updated to latest versions
bun.lock
=> 🚑 hotfix: dependencies in bun.lock to latest versions

Dockerfile, src/application/dtos/jobOpportunity.dto.ts, tsconfig.json
=> More fixes since branching is weird

src/tests/integration/logIn/loginStudent.test.ts
Creation of the file logInStudent.test.ts which includes de use cases of:
- should login as student
- should login as studentand return the jwt
- should deny login using nonexisting student credentials
=> ✨:(86a7d5kgh): creation of student login test

.github/workflows/ci-test.yml, src/infrastructure/config/config.ts, src/tests/integration/logIn/logInViewer.test.ts
Create de new login tests for Viewer type and add comment lines for login Admin tests with the expected acces and refresh token from the cookis
=> ✅ test (86a7d5kgh) viewer login test and corrections of login admin test

src/presentation/routes/educationalInstitution.router.ts, src/presentation/routes/major.router.ts, src/presentation/routes/user.router.ts, src/tests/integration/crud/infoManagerCrud.test.ts, src/tests/integration/crud/studentCrud.test.ts, src/tests/integration/crud/tutorCrud.test.ts, src/tests/integration/crud/universityCrud.test.ts
✅ (86a7rekh0): Implementation of CRUD testion for info manager user
* The task of of view mayor still remains
✅(86a7rear0): Implementation of CRUD testing for university user
* The task of main screen university user still remains
✅(86a7reqcq): Implementation of CRUD testing for tutor user
* The task view related users still remains
✅(86a7rdq3a): Implementation of CRUD testing for student user 
* The task of recover password still remains
=> ✅ (86a7rekh0), (86a7rear0), (86a7reqcq), (86a7rdq3a) instegration test

project_structure.text, src/infrastructure/database/repositories/user.repository.impl.ts, src/presentation/controllers/user.controller.ts, src/presentation/routes/user.router.ts
Fix the user update logic so that discriminator‐specific fields (e.g. last_name on Viewer) are correctly persisted. Previously, findByIdAndUpdate on the base model ignored any keys not defined in the base schema.
---
* UserRepository.update
* UserRouter endpoints
=> ♻️ Refactor: Endpoints in the user router and adding update functionality to all users

.github/workflows/ci-test.yml, bun.lock, src/application/use-cases/user/update-user-by-email.use-case.ts, src/domain/entities/comment.entity.ts, src/domain/entities/educationalInstitution.entity.ts, src/domain/entities/jobOpportunity.entity.ts, src/domain/entities/major.entity.ts, src/presentation/controllers/major.controller.ts, src/tests/integration/crud/financesCrud.test.ts, src/tests/integration/crud/infoManagerCrud.test.ts, src/tests/integration/crud/marketingCrud.test.ts, src/tests/integration/crud/studentCrud.test.ts, src/tests/integration/crud/supportCrud.test.ts, src/tests/integration/crud/tutorCrud.test.ts, src/tests/integration/crud/universityCrud.test.ts, src/tests/integration/logIn/logInViewer.test.ts, src/tests/integration/logIn/loginAdministrator.test.ts, src/tests/integration/logIn/loginStudent.test.ts
=> Develop a Main

src/presentation/routes/user.router.ts
Add special delete route for users with role validation and remove ID-based delete route
=> 🚑 Hotfix: Add special delete route for users with role validation and remove ID-based delete route

src/presentation/routes/subscriptionPlan.routes.ts
Erased role validation for subscription plans listing so subscription plans can be seen on the landing screen
- src/presentation/routes/subscriptionPlan.routes.ts
=> ♻️  Refactor (86a88q5db): Remove role validation for listing all subscription plans

src/application/dtos/major.dto.ts, src/domain/entities/major.entity.ts, src/infrastructure/database/repositories/major.repository.impl.ts, src/presentation/routes/subscriptionPlan.routes.ts
Fit with CreatedBy field in Major
- src/application/dtos/major.dto.ts
- src/domain/entities/major.entity.ts
- src/infrastructure/database/repositories/major.repository.impl.ts
=> 🐛 Fix major createdby

src/tests/integration/businessLogic/majorComments.test.ts, src/tests/integration/businessLogic/searchEducationalInstitution.test.ts, src/tests/integration/businessLogic/searchJobOpportunity.test.ts, src/tests/integration/businessLogic/studentTest.test.ts, src/tests/integration/crud/financesCrud.test.ts, src/tests/integration/crud/infoManagerCrud.test.ts, src/tests/integration/crud/marketingCrud.test.ts, src/tests/integration/crud/studentCrud.test.ts, src/tests/integration/crud/supportCrud.test.ts, src/tests/integration/crud/tutorCrud.test.ts, src/tests/integration/crud/universityCrud.test.ts
✅(86a88xfaj) search universities
✅(86a88xgbf) search mayors
✅search job opportunity
✅vocational test
✅psycometric test
✅partial psycometric test
🐛 All previous crud testing corrected with delete user endpoint change
=> ✅ (86a88xfaj) (86a88xgbf) (86a88xhnw) (86a88xjhx) (86a88xm8w)

src/tests/integration/businessLogic/getPartialRevenueSubscriptionPlan.test.ts, src/tests/integration/businessLogic/getTotalInvestmentCampaign.test.ts, src/tests/integration/businessLogic/getTotalRevenueSubscriptionPlan.test.ts, src/tests/integration/businessLogic/updateSubscriptionPlan.test.ts
✅ (86a88y01j) update subscription plans test
✅ (86a88y1c0) partial revenue test
✅ (86a88y0q2) total revenue test
✅ (86a88y323) delete tutor account test
✅ (86a88y23e) campaing cost test
=> ✅ (86a88y01j) (86a88y1c0)  (86a88y0q2) (86a88y323) (86a88y23e)

src/application/use-cases/email/SendCuestionaryEmailUseCase.ts, src/application/use-cases/index.ts, src/application/use-cases/studentTest/cuestionary.use-case.ts, src/infrastructure/config/config.ts, src/presentation/controllers/email.controller.ts, src/presentation/controllers/studentTest.controller.ts, src/presentation/routes/email.router.ts, src/presentation/routes/studentTest.router.ts
Funcionality for satisfaction cuestionary was added.
- SendCuestionaryEmailUseCase.ts
- index.ts
- cuestionary.use-case.ts
- config.ts
- email.controller.ts
- StudentTest.controller.ts
- email.router.ts
- StudentTest.router.ts
=> Feature dotnet cuestionary
